os:
  - linux
  - osx
language: node_js
node_js:
  - "node"
  - 10
  - 12
  - 14
  - 16
# env:
#   - CXX=g++-4.8
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.8
